/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SessionPanel.java
 *
 * Created on Dec 16, 2010, 6:44:00 PM
 */
package edubuntututorial.imk.kelompok.view.panel;

import edubuntututorial.FramePlay;
import edubuntututorial.imk.kelompok.controll.panel.SessionControll;
import edubuntututorial.imk.kelompok.listener.panel.SessionListener;
import edubuntututorial.imk.kelompok.model.panel.SessionModel;
import edubuntututorial.imk.kelompok.view.AboutForm;
import edubuntututorial.imk.kelompok.view.PlayView;
import java.io.IOException;

/**
 *
 * @author hendri
 */
public class SessionPanel extends javax.swing.JPanel implements SessionListener {

    private SessionModel model;
    private SessionControll controller;
    private FramePlay framePlay;
    private AboutForm form;

    /** Creates new form SessionPanel */
    public SessionPanel() {
        initComponents();

        model = new SessionModel();
        controller = new SessionControll();

        model.setListener(this);
        controller.setSessionModel(model);
        buttonGlass3.setMnemonic('K');
        buttonGlass4.setMnemonic('T');
    }

    public FramePlay getFramePlay() {
        return framePlay;
    }

    public void setFramePlay(FramePlay framePlay) {
        this.framePlay = framePlay;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelWhiteBorder1 = new from.launk.container.PanelWhiteBorder();
        buttonGlass3 = new from.launk.face.ButtonGlass();
        buttonGlass4 = new from.launk.face.ButtonGlass();
        jLabel1 = new javax.swing.JLabel();

        setOpaque(false);
        setLayout(new java.awt.BorderLayout());

        buttonGlass3.setText("Keluar"); // NOI18N
        buttonGlass3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass3ActionPerformed(evt);
            }
        });

        buttonGlass4.setText("Tentang"); // NOI18N
        buttonGlass4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonGlass4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Stencil", 0, 36));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("E-TUTORIAL EduBuntu 10.10 ");

        javax.swing.GroupLayout panelWhiteBorder1Layout = new javax.swing.GroupLayout(panelWhiteBorder1);
        panelWhiteBorder1.setLayout(panelWhiteBorder1Layout);
        panelWhiteBorder1Layout.setHorizontalGroup(
            panelWhiteBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWhiteBorder1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(buttonGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 269, Short.MAX_VALUE)
                .addComponent(buttonGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );
        panelWhiteBorder1Layout.setVerticalGroup(
            panelWhiteBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelWhiteBorder1Layout.createSequentialGroup()
                .addGroup(panelWhiteBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelWhiteBorder1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(buttonGlass4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelWhiteBorder1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(panelWhiteBorder1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonGlass3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        add(panelWhiteBorder1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonGlass4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass4ActionPerformed
        // TODO add your handling code here:
        controller.onAbout();

    }//GEN-LAST:event_buttonGlass4ActionPerformed

    private void buttonGlass3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonGlass3ActionPerformed
        // TODO add your handling code here:
        controller.onExit();
    }//GEN-LAST:event_buttonGlass3ActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private from.launk.face.ButtonGlass buttonGlass3;
    private from.launk.face.ButtonGlass buttonGlass4;
    private javax.swing.JLabel jLabel1;
    private from.launk.container.PanelWhiteBorder panelWhiteBorder1;
    // End of variables declaration//GEN-END:variables

    public void onExit() {

        System.exit(0);

    }

    public void About() {
        if (form == null) {
            form = new AboutForm(null, true);

        }

        try {
            framePlay.setPlayPanel1(5);

        } catch (IOException ex) {
            ex.printStackTrace();
        }
        form.setLocation(250, 50);
        form.setVisible(true);
        
        

    }

    public void onSesiSatu() {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
