/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PlayView.java
 *
 * Created on Dec 16, 2010, 10:15:50 AM
 */
package edubuntututorial.imk.kelompok.view;

import edubuntututorial.FramePlay;
import edubuntututorial.imk.kelompok.MediaPlayer;
import edubuntututorial.imk.kelompok.view.panel.SessionPanel;
import edubuntututorial.imk.kelompok.view.panel.sesi.SesiSatuPanel;
import from.launk.container.PanelGlass;

/**
 *
 * @author hendri
 */
public class PlayView extends javax.swing.JPanel {

    private MediaPlayer mediaPlayer;
    private SesiSatuPanel satuPanel;
    private FramePlay framePlay;

    /** Creates new form PlayView */
    public PlayView() {


        initComponents();

        sesiSatuPanel1.setPlayView(this);


    }

    public FramePlay getFramePlay() {
        return framePlay;
    }

    public void setFramePlay(FramePlay framePlay) {
        this.framePlay = framePlay;
    }

    public SessionPanel getSessionPanel1() {
        return sessionPanel1;
    }

    public void setSessionPanel1(SessionPanel sessionPanel1) {
        this.sessionPanel1 = sessionPanel1;
    }

    public SesiSatuPanel getSesiSatuPanel1() {
        return sesiSatuPanel1;
    }

    public void setSesiSatuPanel1(SesiSatuPanel sesiSatuPanel1) {
        this.sesiSatuPanel1 = sesiSatuPanel1;
    }

    public PanelGlass getPlayPanel() {
        return playPanel;
    }

    public void setPlayPanel(PanelGlass playPanel) {
        this.playPanel = playPanel;
    }

    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        warnaComp21 = new edubuntututorial.imk.kelompok.widget.WarnaComp2();
        panelOval1 = new from.launk.container.PanelOval();
        panelLine1 = new from.launk.container.PanelLine();
        panelWhiteBorder2 = new from.launk.container.PanelWhiteBorder();
        panelOval2 = new from.launk.container.PanelOval();
        panelWhiteBorder3 = new from.launk.container.PanelWhiteBorder();
        warnaComp22 = new edubuntututorial.imk.kelompok.widget.WarnaComp2();
        panelOval3 = new from.launk.container.PanelOval();
        panelOval4 = new from.launk.container.PanelOval();
        playPanel = new from.launk.container.PanelGlass();
        panelWhiteBorder4 = new from.launk.container.PanelWhiteBorder();
        jPanel7 = new javax.swing.JPanel();
        sesiSatuPanel1 = new edubuntututorial.imk.kelompok.view.panel.sesi.SesiSatuPanel();
        jPanel8 = new javax.swing.JPanel();
        sessionPanel1 = new edubuntututorial.imk.kelompok.view.panel.SessionPanel();

        setLayout(new java.awt.BorderLayout());

        warnaComp21.setLayout(new java.awt.BorderLayout());

        panelOval1.setLayout(new java.awt.BorderLayout());

        panelWhiteBorder2.setPreferredSize(new java.awt.Dimension(774, 450));
        panelWhiteBorder2.setLayout(new javax.swing.BoxLayout(panelWhiteBorder2, javax.swing.BoxLayout.LINE_AXIS));

        panelOval2.setLayout(new java.awt.BorderLayout());

        panelWhiteBorder3.setPreferredSize(new java.awt.Dimension(600, 450));
        panelWhiteBorder3.setLayout(null);

        warnaComp22.setLayout(new java.awt.BorderLayout());

        panelOval3.setLayout(new java.awt.BorderLayout());

        panelOval4.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout playPanelLayout = new javax.swing.GroupLayout(playPanel);
        playPanel.setLayout(playPanelLayout);
        playPanelLayout.setHorizontalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );
        playPanelLayout.setVerticalGroup(
            playPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 390, Short.MAX_VALUE)
        );

        panelOval4.add(playPanel, java.awt.BorderLayout.CENTER);

        panelOval3.add(panelOval4, java.awt.BorderLayout.CENTER);

        warnaComp22.add(panelOval3, java.awt.BorderLayout.CENTER);

        panelWhiteBorder3.add(warnaComp22);
        warnaComp22.setBounds(30, 30, 580, 390);

        panelOval2.add(panelWhiteBorder3, java.awt.BorderLayout.CENTER);

        panelWhiteBorder2.add(panelOval2);

        panelWhiteBorder4.setPreferredSize(new java.awt.Dimension(250, 450));
        panelWhiteBorder4.setLayout(new java.awt.CardLayout());

        jPanel7.setOpaque(false);
        jPanel7.setLayout(new java.awt.CardLayout());
        jPanel7.add(sesiSatuPanel1, "card2");

        panelWhiteBorder4.add(jPanel7, "card8");

        jPanel8.setOpaque(false);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );

        panelWhiteBorder4.add(jPanel8, "card9");

        panelWhiteBorder2.add(panelWhiteBorder4);

        panelLine1.add(panelWhiteBorder2, java.awt.BorderLayout.PAGE_START);

        sessionPanel1.setPreferredSize(new java.awt.Dimension(900, 220));
        panelLine1.add(sessionPanel1, java.awt.BorderLayout.CENTER);

        panelOval1.add(panelLine1, java.awt.BorderLayout.CENTER);

        warnaComp21.add(panelOval1, java.awt.BorderLayout.CENTER);

        add(warnaComp21, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private from.launk.container.PanelLine panelLine1;
    private from.launk.container.PanelOval panelOval1;
    private from.launk.container.PanelOval panelOval2;
    private from.launk.container.PanelOval panelOval3;
    private from.launk.container.PanelOval panelOval4;
    private from.launk.container.PanelWhiteBorder panelWhiteBorder2;
    private from.launk.container.PanelWhiteBorder panelWhiteBorder3;
    private from.launk.container.PanelWhiteBorder panelWhiteBorder4;
    private from.launk.container.PanelGlass playPanel;
    private edubuntututorial.imk.kelompok.view.panel.sesi.SesiSatuPanel sesiSatuPanel1;
    private edubuntututorial.imk.kelompok.view.panel.SessionPanel sessionPanel1;
    private edubuntututorial.imk.kelompok.widget.WarnaComp2 warnaComp21;
    private edubuntututorial.imk.kelompok.widget.WarnaComp2 warnaComp22;
    // End of variables declaration//GEN-END:variables
}
